name: read_banking_slip
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # OCR
  tesseract_ocr:
    path: plugins/tesseract_ocr/tesseract_ocr-0.5.0
  
  google_mlkit_text_recognition: ^0.15.0   # ✅ ล่าสุดจริง

  # State management
  provider: ^6.1.2

  # Local database
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  path: ^1.9.0

  # Utilities
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  image: ^4.2.0

  # Media & OCR
  image_picker: ^1.1.2
  
  # Permissions
  permission_handler: ^11.3.1

  # Optional
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0   # ✅ รองรับ SDK 3.9

flutter:
  uses-material-design: true
  assets:
    - assets/tessdata/
    - assets/tessdata_config.json
    # - assets/tessdata/tha.traineddata
    # - assets/tessdata/eng.traineddata

